=== SebaUbuntu/hs/5/TDP/3. XML/3. libri/libri.dtd
<!ELEMENT libri (libreria, libro+)>
<!ELEMENT libreria (#PCDATA)>
<!ELEMENT libro (autore+, titolo, editore, prezzo?)>
<!ELEMENT autore (#PCDATA)>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT editore (#PCDATA)>
<!ELEMENT prezzo (#PCDATA)>
<!ATTLIST libri aggiornamento CDATA #REQUIRED>
<!ATTLIST libreria nome CDATA #REQUIRED>
<!ATTLIST libreria indirizzo CDATA #REQUIRED>
<!ATTLIST libro codice CDATA #REQUIRED>
<!ATTLIST editore anno CDATA #IMPLIED>
<!ATTLIST prezzo valuta CDATA #REQUIRED>

=== SebaUbuntu/hs/5/TDP/3. XML/3. libri/libri.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libri SYSTEM "libri.dtd">
<libri aggiornamento="25/11/2009">
  <libreria nome="Librissimi" indirizzo="Via Adda, 3" />
  <libro codice="id0001"> 
    <autore>J.K. Rowlings</autore> 
    <titolo>Harry Potter e la pietra filosofale</titolo> 
    <editore anno="1997">Salani</editore> 
  </libro>
  <libro codice="id0002"> 
    <autore>J.R. Tolkien</autore>
    <autore>J.R. Tolkien</autore>
    <titolo>Il signore degli Anelli</titolo> 
    <editore>Bompiani</editore>
    <prezzo valuta="euro">24</prezzo> 
  </libro>
</libri>
